const products=getProducts(),business=getBusiness();const path=location.pathname.split("/").pop()||"index.html";const app=document.getElementById("app");function side(){return `<aside class="sidebar"><div class="brand">ORDERIN</div><div class="side-links"><a href="index.html">📊 Dashboard</a><a href="orders.html">🧾 Pesanan</a><a href="products.html">📦 Produk</a><a href="categories.html">🏷️ Kategori</a><a href="settings.html">⚙️ Pengaturan</a><a href="../index.html">↗ Lihat Website</a></div></aside>`}
function layout(content){app.innerHTML=`<div class="admin-layout">${side()}<main class="admin-main">${content}</main></div>`}
function dashboard(){let orders=getOrders(),rev=orders.filter(o=>o.status!=="Dibatalkan").reduce((a,o)=>a+o.total,0);layout(`<div class="section-head"><div><div class="eyebrow">ADMIN</div><h1>Dashboard</h1></div></div><div class="stats"><div class="stat">Pesanan hari ini<strong>${orders.length}</strong></div><div class="stat">Baru<strong>${orders.filter(o=>o.status==="Baru").length}</strong></div><div class="stat">Selesai<strong>${orders.filter(o=>o.status==="Selesai").length}</strong></div><div class="stat">Omzet<strong>${money(rev)}</strong></div></div><section class="section"><h2>Pesanan terbaru</h2>${orderTable(orders.slice().reverse().slice(0,8))}</section>`)}
function orderTable(orders){if(!orders.length)return `<div class="empty">Belum ada pesanan.</div>`;return `<div class="table-wrap"><table class="table"><thead><tr><th>Order</th><th>Customer</th><th>Total</th><th>Status</th><th>Aksi</th></tr></thead><tbody>${orders.map(o=>`<tr><td><b>${o.id}</b><br><small>${new Date(o.createdAt).toLocaleString("id-ID")}</small></td><td>${o.customer.name}<br><small>${o.customer.phone}</small></td><td>${money(o.total)}</td><td><span class="badge">${o.status}</span></td><td><select onchange="statusOrder('${o.id}',this.value)">${["Baru","Diproses","Selesai","Dibatalkan"].map(s=>`<option ${s===o.status?"selected":""}>${s}</option>`).join("")}</select></td></tr>`).join("")}</tbody></table></div>`}
window.statusOrder=(id,status)=>{let o=getOrders();let x=o.find(x=>x.id===id);if(x){x.status=status;saveOrders(o);location.reload()}}
function ordersPage(){let orders=getOrders().slice().reverse();layout(`<div class="section-head"><div><div class="eyebrow">ORDER</div><h1>Pesanan</h1></div></div>${orderTable(orders)}`)}
function productsPage(){let p=getProducts();layout(`<div class="section-head"><div><div class="eyebrow">CATALOG</div><h1>Produk</h1></div><button class="primary" onclick="addProduct()">+ Tambah Produk</button></div><div class="table-wrap"><table class="table"><thead><tr><th>Produk</th><th>Kategori</th><th>Harga</th><th>Aksi</th></tr></thead><tbody>${p.map(x=>`<tr><td>${x.emoji} <b>${x.name}</b></td><td>${x.category}</td><td>${money(x.price)}</td><td><button class="secondary" onclick="editProduct(${x.id})">Edit</button> <button class="secondary" onclick="deleteProduct(${x.id})">Hapus</button></td></tr>`).join("")}</tbody></table></div>`)}
window.addProduct=()=>{let name=prompt("Nama produk?");if(!name)return;let price=Number(prompt("Harga?","25000"));let category=prompt("Kategori?","Makanan");let emoji=prompt("Emoji produk?","🍱");let p=getProducts();p.push({id:Date.now(),name,price,category,emoji,description:"Produk baru ORDERIN"});saveProducts(p);location.reload()}
window.editProduct=id=>{let p=getProducts(),x=p.find(x=>x.id==id);if(!x)return;x.name=prompt("Nama",x.name)||x.name;x.price=Number(prompt("Harga",x.price))||x.price;x.category=prompt("Kategori",x.category)||x.category;saveProducts(p);location.reload()}
window.deleteProduct=id=>{if(confirm("Hapus produk ini?")){saveProducts(getProducts().filter(x=>x.id!=id));location.reload()}}
function categoriesPage(){let cats=[...new Set(getProducts().map(x=>x.category))];layout(`<div class="section-head"><div><div class="eyebrow">KATEGORI</div><h1>Kategori</h1></div></div><div class="panel">${cats.map(c=>`<div class="cart-row"><div class="grow"><b>${c}</b></div><span class="badge">${getProducts().filter(x=>x.category===c).length} produk</span></div>`).join("")}</div>`)}
function settingsPage(){let b=getBusiness();layout(`<div class="section-head"><div><div class="eyebrow">SETTINGS</div><h1>Pengaturan Bisnis</h1></div></div><div class="panel"><form id="settings" class="form-grid"><label>Nama Bisnis<input name="name" value="${b.name}"></label><label>Tagline<input name="tagline" value="${b.tagline}"></label><label>WhatsApp (format 628...)<input name="phone" value="${b.phone}"></label><label>Alamat<input name="address" value="${b.address}"></label><label>Jam Buka<input name="hours" value="${b.hours}"></label><button class="primary">Simpan</button></form></div>`);document.getElementById("settings").onsubmit=e=>{e.preventDefault();let f=new FormData(e.target);localStorage.setItem("orderin_business",JSON.stringify(Object.fromEntries(f)));alert("Pengaturan tersimpan");}}
if(path==="orders.html")ordersPage();else if(path==="products.html")productsPage();else if(path==="categories.html")categoriesPage();else if(path==="settings.html")settingsPage();else dashboard();
