-- Jalankan seluruh file ini di Supabase SQL Editor.
create table if not exists public.products (
 id bigint generated by default as identity primary key,
 name text not null, category text not null, price numeric not null default 0,
 emoji text default '🍽️', description text default '', variants jsonb default '[]'::jsonb,
 available boolean default true, bestseller boolean default false,
 created_at timestamptz not null default now()
);
create table if not exists public.orders (
 id text primary key, customer_name text not null, customer_phone text not null,
 customer_address text default '', customer_note text default '', items jsonb not null,
 total numeric not null default 0, status text not null default 'Baru',
 created_at timestamptz not null default now()
);
alter table public.products enable row level security;
alter table public.orders enable row level security;
drop policy if exists "public read available products" on public.products;
create policy "public read available products" on public.products for select using (available=true);
drop policy if exists "authenticated manage products" on public.products;
create policy "authenticated manage products" on public.products for all to authenticated using(true) with check(true);
drop policy if exists "public create orders" on public.orders;
create policy "public create orders" on public.orders for insert to anon,authenticated with check(true);
drop policy if exists "authenticated manage orders" on public.orders;
create policy "authenticated manage orders" on public.orders for all to authenticated using(true) with check(true);
